### ISSUE TITLE
Tracking image

### ISSUE THREAD

**Issue by sorenharfagri** [WebAR-rocks/WebAR.rocks.face#27]
Hello, Thanks for the incredible work, library is awesome!

I'm trying to adapt a react glasses demo to work with uploaded picture, instead of a video camera capture, is there any way or example?

**Comment by xavierjs** [comment]
Hi,

It is possible, take a look at this demo: https://github.com/WebAR-rocks/WebAR.rocks.face/tree/master/demos/faceReplacement/gif

**Comment by sorenharfagri** [comment]
I made this by creating a gl texture from my photo, then directly setting _glVideoTexture in WebARRocksFaceThreeHelper, and passing it to WEBARROCKSFACE.set_inputTexture().

Is there possibility to not request user videocam?

**Comment by xavierjs** [comment]
If you set `videoSettings` init argument to `null`, the user camera should not be requested (more info here: https://github.com/WebAR-rocks/WebAR.rocks.face#optional-init-arguments )
