### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by brunomaffei** [WebAR-rocks/WebAR.rocks.face#29]
I'm opening this issue to see if anyone else is having this problem or has had it solved. Thanks in advance.

![image](https://user-images.githubusercontent.com/47982525/123287046-d40a2a00-d4e4-11eb-8369-1993e139f09a.png)

**Comment by xavierjs** [comment]
It seems to be platform-specific. I have just cloned a fresh new repository (I am on Ubuntu 18.04LTS) and everything goes fine. Here are the commands I entered in the shell:

```bash
git clone git@github.com:WebAR-rocks/WebAR.rocks.face.git
cd WebAR.rocks.face/
cd reactThreeFiberDemos/
npm install
npm run start
```

You can try to remove the `node_modules` directory and rerun `npm install`

**Comment by brunomaffei** [comment]
Run start it's okay but when I try npm run build show me this error.

**Comment by xavierjs** [comment]
`npm build` is not supported. It is an integration sample, it is not a full webapp.

**Comment by xavierjs** [comment]
I have added the lacking deps

**Comment by brunomaffei** [comment]
hmmm good

**Comment by brunomaffei** [comment]
@xavierjs I wanted to fix the camera because by default it comes with a bad quality, is there any possibility to fix this?

**Comment by xavierjs** [comment]
Read the doc: https://github.com/WebAR-rocks/WebAR.rocks.face#optional-init-arguments
