### ISSUE TITLE
how to override default video resolution

### ISSUE THREAD

**Issue by mohitsavani117** [WebAR-rocks/WebAR.rocks.face#33]
hi, i want to change the video resolution programatically

**Comment by xavierjs** [comment]
Hi

To ask for a higher video resoluton in the WebAR.rocks.face glasses demo, here: https://github.com/WebAR-rocks/WebAR.rocks.face/blob/9c9ffed3842785c2504bab0110fdc2546fbb7f2c/demos/VTOGlasses/main.js#L23
at the same level as NNCPath, you can add:

`ˋ`
videoSettings: {
  idealWidth: 1280,
  idealHeight: 720
}
`ˋ`

This property is also describe in the README of the lib. Please read it carefully: https://github.com/WebAR-rocks/WebAR.rocks.face#optional-init-arguments

**Comment by xavierjs** [comment]
@mohitsavani117 did it work? Can I close this issue?
