### ISSUE TITLE
react-three-fiber and webARRocks related issue

### ISSUE THREAD

**Issue by mohitsavani117** [WebAR-rocks/WebAR.rocks.face#34]
hi i am work on AR with face filter app in react js. i make two canvas:-
1) for glasses on user face this canvas import from react-three-fiber
2) for video which is from WebARRocks for face canvas
now when i override default height and width for better resolution in face canvas then glasses canvas position was affected it doesnt show glasses properly on face.

**Comment by mohitsavani117** [comment]
please check it out my code:-
https://github.com/Design2k/webAR-issue.git

**Comment by xavierjs** [comment]
I think that you confuse the display size of canvas (CSS size) and the canvas resolution. There are some mistakes in your code, I will fix them. However, in the future, I will have to charge for that since it is custom development and integration.

**Comment by xavierjs** [comment]
Hi @mohitsavani117

I have fixed the glasses 2D offset issue, updated WebAR.rocks.face to the latest version (less latency, more efficient), and also fixed a bug on how sizing is computed (previously it was zooming on the face).
Unfortunately you have deleted your `webAR-issue` repo so I cannot submit a PR.

So I have created a new private Github repo and sent you an invite: https://github.com/xavierjs/webAR-issue

This commit groups my changes: https://github.com/xavierjs/webAR-issue/commit/cb4418869c088eb19f305e0e3b0f13aa7f77f2a4

Please tell me if it helps to solve your issue or not.

**Comment by mohitsavani117** [comment]
hi @xavierjs 
sorry for not replying you and thank you for this i will integrate this code and check if it solve my issue or not.

**Comment by mohitsavani117** [comment]
ohk
