### ISSUE TITLE
GIF Face replacement does not work on externally loaded GIFs

### ISSUE THREAD

**Issue by kravczyk** [WebAR-rocks/WebAR.rocks.face#38]
Hi,

I was testing GIF Face replacement demo (both live and downloaded code) and I noticed that face positions calculated on loaded GIFs are completely incorrect or not found. It does not work even on GIFs placed as examples. Could you confirm that the demo is broken or am I doing something wrong?

I was experimenting with GIF Face replacement demo to learn how to track a single image instead of a webcam stream or a video. If you have a working example on that, it would be very appreciated!

**Comment by xavierjs** [comment]
Hi,

Thank you for signaling this bug. It should work now

**Comment by kravczyk** [comment]
It works, thanks :)

**Comment by hmachefe** [comment]
Thanks a lot xavier@theRescue
