### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by jelling** [WebAR-rocks/WebAR.rocks.face#39]
Are there any performance benchmarks for how rocks.face compares to Mediapipe or other browser based mocap solutions?

**Comment by xavierjs** [comment]
Hi @jelling 

AFAIK there is no performance benchmarks to compare different webar solutions (for face tracking or even image tracking for which there are even more solutions available). It would be difficult to do a simple benchmark for these reasons:

* The performance of the techs is highly platform dependant. Some are running more on the GPU, others on the CPU. WebAR.rocks.face is using mostly GPU computing power. However, the GPU architecture changes a lot between GPU markers.
* Comparing the tech is not obvious. The landmarks are often not the same. There is often a trade-off between accuracy and performance.
* We also have to take into account the robustness of the library, it should work under different lighting conditions, with different skin colors, and with beards (ASM algorithms like BRFv5 can struggle with beards for example). it should work with large head rotation angles.
* Stabilization of landmarks has to be taken into account.

Globally, Google Facemesh (relying on Mediapipe) is very accurate. However, it is slower than WebAR.rocks.face and it uses more resources. What are you looking for?

**Comment by jelling** [comment]
Thank you! That was very helpful.
