### ISSUE TITLE
 Inquiry Regarding VTOGlasses Model Compatibility

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [WebAR-rocks/WebAR.rocks.face#60]
Hi WebAR Rocks team,

First of all, I want to express my gratitude for the amazing work you’re doing. I’ve been using your library for a project, and it’s been a fantastic experience!

I am currently working with the VTOGlasses demo, and I’ve noticed that the provided GLB models work perfectly. However, I have some custom models that do not seem to function as expected. Could you clarify what the specific characteristics or requirements are for the glasses models to work correctly with the demo?

I would love to understand the necessary parameters or settings that ensure model compatibility.

Thanks again for all your hard work!

**Comment by EM-LilianaIturribarria** [comment]
duh! sorry, closing this as i just found the documentation: https://github.com/WebAR-rocks/WebAR.rocks.face/tree/master/demos/VTOGlasses

thank you again for your work!

**Comment by xavierjs** [comment]
You are welcome :)

**Comment by dev76-c** [comment]
> duh! sorry, closing this as i just found the documentation: https://github.com/WebAR-rocks/WebAR.rocks.face/tree/master/demos/VTOGlasses
> 
> thank you again for your work!

I got I want understand do I need to even .blend file in the directory or just the 3d model with .glb file and I want to understand even this if I have 3d model everytime i should make sure with the their co-oridinates and make them proper....??
